version: "3.9"
services:
  redis:
    container_name: redis_kaboom
    image: "redis:6.2.1-alpine"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure